apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-datahub
  name: alameda-datahub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-datahub
subjects:
- kind: ServiceAccount
  name: alameda-datahub
  namespace: alameda
