apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-datahub
  name: alameda-datahub
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  verbs:
  - get
  - list
  - patch
  - create
- apiGroups:
  - autoscaling.containers.ai
  resources:
  - alamedarecommendations
  verbs:
  - get
  - update
