apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-datahub
  name: alameda-datahub
  namespace: alameda
spec:
  ports:
  - name: grpc
    port: 50050
    protocol: TCP
    targetPort: 50050
  selector:
    app: alameda
    component: alameda-datahub
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
