apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    chart: grafana-3.8.4
    heritage: Tiller
    release: alameda-grafana
  name: alameda-grafana-clusterrole
rules: []
