apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    chart: grafana-3.8.4
    heritage: Tiller
    release: alameda-grafana
  name: alameda-grafana
  namespace: alameda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alameda-grafana
subjects:
- kind: ServiceAccount
  name: alameda-grafana
  namespace: alameda
