apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-ai
  name: alameda-ai
  namespace: alameda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alameda
      component: alameda-ai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alameda
        component: alameda-ai
    spec:
      containers:
      - env:
        - name: DATAHUB_ADDRESS
          value: alameda-datahub.alameda:50050
        - name: PREDICT_QUEUE_ENABLED
          value: "true"
        - name: MAXIMUM_PREDICT_PROCESSES
          value: "8"
        - name: PREDICT_QUEUE_URL
          value: amqp://admin:adminpass@alameda-rabbitmq.alameda:5672
        image: quay.io/prophetstor/alameda-ai:latest
        imagePullPolicy: IfNotPresent
        name: ai
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alameda-ai
      serviceAccountName: alameda-ai
      terminationGracePeriodSeconds: 30
status: {}
