apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: admission-controller
  name: alameda-admission-controller
  namespace: alameda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alameda
      component: admission-controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alameda
        component: admission-controller
    spec:
      containers:
      - env:
        - name: NAMESPACE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: ALAMEDA_ADMCTL_CACERTFILE
          value: /etc/tls-certs/ca.crt
        - name: ALAMEDA_ADMCTL_TLSCERTFILE
          value: /etc/tls-certs/tls.crt
        - name: ALAMEDA_ADMCTL_TLSPRIVATEKEYFILE
          value: /etc/tls-certs/tls.key
        - name: ALAMEDA_ADMCTL_DEPLOYEDNAMESPACE
          value: alameda
        - name: ALAMEDA_ADMCTL_ENABLE
          value: "false"
        - name: ALAMEDA_ADMCTL_DATAHUB_ADDRESS
          value: alameda-datahub.alameda:50050
        image: quay.io/prophetstor/alameda-admission-ubi:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/admission-controller
            - probe
            - --type=liveness
          failureThreshold: 20
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: admission-controller
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/admission-controller
            - probe
            - --type=readiness
          failureThreshold: 20
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/tls-certs
          name: tls-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alameda-admission-controller
      serviceAccountName: alameda-admission-controller
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tls-certs
        secret:
          defaultMode: 420
          secretName: alameda-admission-controller-tls
status: {}
