apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: admission-controller
  name: admission-controller
  namespace: alameda
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8000
  selector:
    app: alameda
    component: admission-controller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
