{
 "title": "VPA Recommendation",
 "time": { "from": "now-1h", "to": "now+15m" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "resource", "label": "Scope", "query": "Application, Container" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "show tag values on alameda_cluster_status from pod with key = \"namespace\" where alameda_scaler_scaling_tool = 'VPA'"
   },
   {
    "name": "scaler",
    "label": "Application",
    "query": "show tag values on alameda_cluster_status from pod with key = \"alameda_scaler_name\" where \"namespace\" =~ /^[[ns]]$/ and alameda_scaler_scaling_tool= 'VPA'"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..pod where \"namespace\" =~ /^[[ns]]$/ and \"alameda_scaler_name\" =~ /^[[scaler]]$/ and 'Container' = '$resource' "
   },
   {
    "name": "container",
    "label": "Container",
    "query": "show tag values on alameda_cluster_status from container with key=\"name\" where \"namespace\" = '$ns' and \"pod_name\" = '$pod'"
   },
   {
    "name": "h_pod",
    "label": "pod",
    "query": "select \"name\", \"policy\" from (select \"name\", \"policy\" from alameda_cluster_status..pod where \"namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and 'Application' = '$resource' group by \"name\" order by time desc limit 1), (select \"name\", \"policy\" from alameda_cluster_status..pod where \"namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and  \"name\" = '$pod' and 'Container' = '$resource' group by \"name\" order by time desc limit 1) order by time desc"
   },
   {
    "name": "h_container",
    "query": "select \"name\", resource_limit_cpu from ( select \"name\", resource_limit_cpu from alameda_cluster_status..container where \"namespace\" = '$ns' and alameda_scaler_name = '$scaler' and \"pod_name\" =~ /^[[h_pod]]$/ and 'Application' = '$resource' group by \"name\" order by time desc limit 1), ( select \"name\", resource_limit_cpu from alameda_cluster_status..container where \"namespace\" = '$ns' and alameda_scaler_name = '$scaler' and \"pod_name\" = '$pod' and \"name\" = '$container' and 'Container' = '$resource' group by \"name\" order by time desc limit 1) order by time desc"
   },
   {
    "name": "count_container",
    "query": "select count(\"name\") from (select \"name\", resource_request_cpu from (select \"name\", resource_request_cpu from alameda_cluster_status..container where namespace = '$ns' and alameda_scaler_name = '$scaler' and \"pod_name\" =~ /^[[h_pod]]$/ and 'Application' = '$resource'), (select \"name\", resource_request_cpu from alameda_cluster_status..container where namespace = '$ns' and alameda_scaler_name = '$scaler' and \"pod_name\" = '$pod' and \"name\" = '$container' and 'Container' = '$resource'))"
   },
   { "name": "recomInterval", "query": "30s" },
   {
    "name": "preloader",
    "label": "Preloader",
    "query": "select preloader from alameda_metric..grafana_config order by time desc limit 1"
   },
   {
    "name": "all_ns",
    "query": "show tag values on alameda_cluster_status from pod with key = \"namespace\" where alameda_scaler_scaling_tool = 'VPA'"
   },
   {
    "name": "all_scaler",
    "query": "show tag values on alameda_cluster_status from pod with key = \"alameda_scaler_name\" where \"namespace\" =~ /^[[all_ns]]$/ and alameda_scaler_scaling_tool = 'VPA'"
   },
   {
    "name": "all_pod",
    "query": "show tag values on alameda_cluster_status from pod with key = \"name\" where \"namespace\" =~ /^[[all_ns]]$/ and \"alameda_scaler_name\" =~ /^[[all_scaler]]$/"
   },
   {
    "name": "app_ns",
    "query": "select namespace, \"policy\" from alameda_cluster_status..pod where alameda_scaler_scaling_tool = 'VPA' and 'Application' = '$resource' and namespace = '$ns' and ('false' = '$preloader' or '' = '$preloader') group by \"namespace\" order by time desc limit 1"
   },
   {
    "name": "container_ns",
    "query": "select namespace, \"policy\" from alameda_cluster_status..pod where alameda_scaler_scaling_tool = 'VPA' and namespace = '$ns' and 'Container' = '$resource' and ('false' = '$preloader' or '' = '$preloader') group by \"namespace\" order by time desc limit 1"
   },
   {
    "name": "controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\")"
   },
   {
    "name": "deployment_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"kind\" = 'DEPLOYMENT'"
   },
   {
    "name": "deploymentConfig_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"kind\" = 'DEPLOYMENTCONFIG'"
   },
   {
    "name": "statefulset_controller",
    "query": "select \"name\", \"policy\" from alameda_cluster_status..controller where alameda_scaler_name = '$scaler' and namespace = '$ns' and ('false' = \"$preloader\" or '' = \"$preloader\") and \"kind\" = 'STATEFULSET'"
   },
   {
    "name": "deployment_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "deploymentConfig_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "statefulset_pod",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate, pod_name)"
   },
   {
    "name": "app_container",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{pod_name=~ \"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", container_name != \"POD\"}, container_name)"
   },
   {
    "name": "memorys_deployment_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "memorys_deploymentConfig_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "memorys_statefulset_pod",
    "query": "label_values(container_memory_usage_bytes, pod_name)"
   },
   {
    "name": "app_container",
    "query": "label_values(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{pod_name=~ \"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", container_name != \"POD\"}, container_name)"
   },
   {
    "name": "memorys_app_container",
    "query": "label_values(container_memory_usage_bytes{pod_name=~ \"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", container_name != \"POD\"}, container_name)"
   }
  ]
 },
 "panels": [
  { "title": "Managed Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Managed Containers",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select restart_count, \"name\" as \"container\",  \"namespace\", \"pod_name\" as pod, \"node_name\" as node from alameda_cluster_status..container where \"pod_name\" =~ /^[[all_pod]]$/ and \"namespace\" =~ /^[[all_ns]]$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select \"policy\", \"alameda_scaler_name\" as \"alameda scaler\", \"name\" as pod from alameda_cluster_status..pod where (\"name\" =~ /^[[all_pod]]$/ and \"namespace\" =~ /^[[all_ns]]$/) or ('Container' = '$resource' and scaling_tool= 'VPA')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Managed Nodes",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select create_time *1000 , \"name\", node_cpu_cores, node_memory_bytes, in_cluster from alameda_cluster_status..node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Container Resource Usage and Recommendation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "CPU: Observation, Prediction, and Recommendation (in CPU milicore)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(1000 * max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$app_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\"}[30s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum(1000 * max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$container_ns\", namespace!=\"\", pod_name=\"$pod\", container_name=\"$container\", pod_name!=\"\", container_name!=\"POD\"}[30s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "alias": "Recommendation: CPU Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum from \n(select sum(resource_limit_cpu) from \"alameda_recommendation\"..\"container\" where granularity = '30' and ((\"name\" =~ /^[[app_container]]$/  and '$app_container' != '()') or (\"name\" =~ /^[[h_container]]$/  and '$h_container' != '()') ) and (\"pod_name\" =~ /^($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$/) and \"namespace\" = '$ns'  and time>=now()-1h and time < now() and 'Application' = '$resource' group by time($recomInterval)  fill(none)),\n(select sum(resource_limit_cpu) from \"alameda_recommendation\"..\"container\" where granularity = '30' and \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND time>=now()-1h and time < now() and 'Container' = '$resource' group by time($recomInterval)  fill(none)),\n(select sum from (select sum(resource_limit_cpu),count(resource_limit_cpu) from \"alameda_recommendation\"..\"container\" where granularity = '30' and \"name\" =~ /^[[h_container]]$/ and \"pod_name\" =~ /^[[h_pod]]$/ and \"namespace\" = '$ns' AND time>=now() and time <= now()+15m group by time($recomInterval) fill(none)) where count = $count_container + 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Recommendation: CPU Request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum from \n(select sum(resource_request_cpu) from \"alameda_recommendation\"..\"container\" where granularity = '30' and ((\"name\" =~ /^[[app_container]]$/  and '$app_container' != '()') or (\"name\" =~ /^[[h_container]]$/  and '$h_container' != '()') ) and (\"pod_name\" =~ /^($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$/) and \"namespace\" = '$ns'  and time>=now()-1h and time < now() and 'Application' = '$resource' group by time($recomInterval)  fill(none)),\n(select sum(resource_request_cpu) from \"alameda_recommendation\"..\"container\" where granularity = '30' and \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND time>=now()-1h and time < now() and 'Container' = '$resource' group by time($recomInterval)  fill(none)),\n (select sum from (select sum(resource_request_cpu ), count(resource_request_cpu) from \"alameda_recommendation\"..\"container\" where granularity = '30' and \"pod_name\" =~ /^[[h_pod]]$/ and \"namespace\" = '$ns'  AND time>=now() and time <= now()+15m group by time($recomInterval) fill(none)) where count = $count_container + 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: CPU Usage",
     "measurement": "node_prediction",
     "query": "select * from\n( select sum(value)from \"alameda_prediction\"..\"application\" where kind = 'raw' and granularity = '30' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 1h and time <= now() + 15m and namespace = '$ns' and \"name\" = '$scaler' and 'Application' = '$resource' group by time(30s)),\n( select sum(value) from \"alameda_prediction\"..\"container\" where kind = 'raw' and granularity = '30' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 1h and time <= now() + 15m and \"name\" = '$container' and pod_name = '$pod' and 'Container' = '$resource' group by time(30s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "node",
       "operator": "=",
       "value": "ip-172-23-1-91.us-east-2.compute.internal"
      },
      { "condition": "AND", "key": "type", "operator": "=", "value": "cpu" }
     ]
    },
    {
     "alias": "Observation: CPU Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(max) from (select max(value) from alameda_metric..application_cpu where \"name\" = '$scaler' and \"namespace\" = '$ns' and $timeFilter and time <= now() and 'true' = '$preloader' and 'Application' = '$resource' group by time(30s)), (select max(value) from alameda_metric..container_cpu where \"pod_name\" = '$pod' and \"pod_namespace\" = '$ns' and \"name\" = '$container' and $timeFilter and time <= now() and 'true' = '$preloader' and 'Container' = '$resource' group by time(30s)) where $timeFilter and time <= now() group by time(30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory: Observation, Prediction, and Recommendation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "round(sum(max_over_time(container_memory_usage_bytes{namespace=\"$app_ns\", namespace!=\"\", pod_name=~\"($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[30s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "expr": "round(sum(max_over_time(container_memory_usage_bytes{namespace=\"$container_ns\", pod_name=\"$pod\", container_name=\"$container\", pod_name!=\"\", container_name!=\"POD\", container_name!=\"\"}[30s])))",
     "legendFormat": "Observation: Memory Usage"
    },
    {
     "alias": "Recommendation: Memory Limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum from \n(select sum(resource_limit_memory) from \"alameda_recommendation\"..\"container\" where granularity = '30' and ((\"name\" =~ /^[[memorys_app_container]]$/  and '$memorys_app_container' != '()') or (\"name\" =~ /^[[h_container]]$/  and '$h_container' != '()') ) and (\"pod_name\" =~ /^($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$/) and \"namespace\" = '$ns'  and time>=now()-1h and time < now() and 'Application' = '$resource' group by time($recomInterval)  fill(none)),\n(select sum(resource_limit_memory) from \"alameda_recommendation\"..\"container\" where granularity = '30' and \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND time>=now()-1h and time < now() and 'Container' = '$resource' group by time($recomInterval)  fill(none)),\n(select sum from (select sum(resource_limit_memory),count(resource_limit_memory) from \"alameda_recommendation\"..\"container\" where granularity = '30' and \"name\" =~ /^[[h_container]]$/ and \"pod_name\" =~ /^[[h_pod]]$/ and \"namespace\" = '$ns' and time>=now() and time <= now()+15m group by time($recomInterval) fill(none)) where count = $count_container + 0)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Recommendation: Memory Request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum from \n(select sum(resource_request_memory) from \"alameda_recommendation\"..\"container\" where granularity = '30' and ((\"name\" =~ /^[[memorys_app_container]]$/  and '$memorys_app_container' != '()') or (\"name\" =~ /^[[h_container]]$/  and '$h_container' != '()') ) and (\"pod_name\" =~ /^($deployment_controller)-[0-9a-z]{8,10}-[0-9a-z]*$|($deploymentConfig_controller)-[0-9]{0,7}-[0-9a-z]*$|($statefulset_controller)-[0-9]+$/) and \"namespace\" = '$ns'  and time>=now()-1h and time < now() and 'Application' = '$resource' group by time($recomInterval)  fill(none)),\n(select sum(resource_request_memory) from \"alameda_recommendation\"..\"container\" where granularity = '30' and \"name\" = '$container' and \"pod_name\" = '$pod' and \"namespace\" = '$ns'  AND time>=now()-1h and time < now() and 'Container' = '$resource' group by time($recomInterval)  fill(none)),\n (select sum from (select sum(resource_request_memory ), count(resource_request_memory) from \"alameda_recommendation\"..\"container\" where granularity = '30' and \"pod_name\" =~ /^[[h_pod]]$/ and \"namespace\" = '$ns'  and time>=now() and time <= now()+15m group by time($recomInterval) fill(none)) where count = $count_container + 0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: Memory Usage",
     "measurement": "node_prediction",
     "query": "select * from \n( select sum(value) from \"alameda_prediction\"..\"application\" where kind = 'raw' and granularity = '30' and \"metric\" = 'memory_usage_bytes' and time >= now() - 1h and time <= now() + 15m and namespace = '$ns' and \"name\" = '$scaler' and 'Application' = '$resource' group by time(30s)),\n( select sum(value) from \"alameda_prediction\"..\"container\" where kind = 'raw' and granularity = '30' and \"metric\" = 'memory_usage_bytes' and time >= now() - 1h and time <= now() + 15m and \"name\" = '$container' and pod_name = '$pod' and 'Container' = '$resource' group by time(30s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Observation: Memory Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(max) from (select max(value) from alameda_metric..application_memory where \"name\" = '$scaler' and \"namespace\" = '$ns' and $timeFilter and time <= now() and 'true' = '$preloader' and 'Application' = '$resource' group by time(30s)), (select max(value) from alameda_metric..container_memory where \"pod_name\" = '$pod' and \"pod_namespace\" = '$ns' and \"name\" = '$container' and $timeFilter and time <= now() and 'true' = '$preloader' and 'Container' = '$resource' group by time(30s)) where $timeFilter and time <= now() group by time(30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}