{
 "title": "Dashboard",
 "time": { "from": "now-1d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "NameSpace",
    "query": "select alameda_scaler_namespace, enable_HPA from alameda_cluster_status..container group by alameda_scaler_namespace"
   },
   {
    "name": "scaler",
    "label": "Application",
    "query": "select alameda_scaler_name, enable_VPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" =~ /^[[ns]]$/"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "select pod_name, enable_VPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" =~ /^[[ns]]$/ and \"alameda_scaler_name\" = '$scaler'"
   },
   {
    "name": "container",
    "label": "container",
    "query": "select \"name\", enable_VPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" =~ /^[[ns]]$/ and \"alameda_scaler_name\" = '$scaler' and \"pod_name\"=~ /^[[pod]]$/"
   },
   {
    "name": "lic_status",
    "query": "select status from alameda_cluster_status..keycode limit 1"
   },
   {
    "name": "lic_expired_time",
    "query": "select expire_timestamp * 1000 from alameda_cluster_status..keycode limit 1"
   },
   {
    "name": "event_level",
    "label": "Event Level",
    "query": "Debug, Info, Warning, Error, Fatal"
   },
   {
    "name": "event_ns",
    "label": "Event Namespace",
    "query": "show tag values on alameda_event from event with key = \"subject_namespace\""
   },
   {
    "name": "debug_condition",
    "query": "EVENT_LEVEL_DEBUG, EVENT_LEVEL_INFO, EVENT_LEVEL_WARNING, EVENT_LEVEL_ERROR, EVENT_LEVEL_FATAL"
   },
   { "name": "info", "query": "Debug, Info" },
   {
    "name": "info_condition",
    "query": "EVENT_LEVEL_INFO, EVENT_LEVEL_WARNING, EVENT_LEVEL_ERROR, EVENT_LEVEL_FATAL"
   },
   { "name": "warning", "query": "Debug, Info, Warning" },
   {
    "name": "warning_condition",
    "query": "EVENT_LEVEL_WARNING, EVENT_LEVEL_ERROR, EVENT_LEVEL_FATAL"
   },
   { "name": "error", "query": "Debug, Info, Warning, Error" },
   {
    "name": "error_condition",
    "query": "EVENT_LEVEL_ERROR, EVENT_LEVEL_FATAL"
   },
   {
    "name": "fatal",
    "query": "Debug, Info, Warning, Error, Fatal"
   },
   {
    "name": "debug_count",
    "query": "select sum(*) from (select count + zero  from (select count(id) from alameda_event..event where level = 'EVENT_LEVEL_DEBUG' and subject_namespace =~ /^[[event_ns]]$/ and $timeFilter), (select count(id) - count(id) as zero from alameda_event..event) fill(0))"
   },
   {
    "name": "info_count",
    "query": "select sum(*) from (select count + zero as info from (select count(id) from alameda_event..event where level = 'EVENT_LEVEL_INFO'  and subject_namespace =~ /^[[event_ns]]$/ and $timeFilter ), (select count(id) - count(id) as zero from alameda_event..event) fill(0))"
   },
   {
    "name": "warning_count",
    "query": "select sum(*) from (select count + zero as info from (select count(id) from alameda_event..event where level = 'EVENT_LEVEL_WARNING' and subject_namespace =~ /^[[event_ns]]$/ and $timeFilter ), (select count(id) - count(id) as zero from alameda_event..event) fill(0))"
   },
   {
    "name": "error_count",
    "query": "select sum(*) from (select count + zero as info from (select count(id) from alameda_event..event where level = 'EVENT_LEVEL_ERROR' and $timeFilter and subject_namespace =~ /^[[event_ns]]$/ ), (select count(id) - count(id) as zero from alameda_event..event) fill(0))"
   },
   {
    "name": "fatal_count",
    "query": "select sum(*) from (select count + zero as info from (select count(id) from alameda_event..event where level = 'EVENT_LEVEL_FATAL' and $timeFilter and subject_namespace =~ /^[[event_ns]]$/ ), (select count(id) - count(id) as zero from alameda_event..event) fill(0))"
   }
  ]
 },
 "panels": [
  {
   "title": "Product",
   "type": "text",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "content": "<table style=\"height:80%;width:100%\">\n  <tr>\n    <td>\n      <div style=\"text-align:center;\">\n        <img style=\"vertical-align:middle;\" src=\"https://i1.wp.com/www.prophetstor.com/wp-content/uploads/2017/05/prophetstor_white_logo.png?fit=143%2C62&ssl=1\">\n        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  \n        <span style=\"vertical-align:middle; font-size:30px;\">Federator.ai</span>\n      </div>\n    </td>\n  </tr>\n</table>\n"
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 4, "w": 8, "x": 9, "y": 0 },
   "content": "<h1 style=\"position: relative; text-align: center; vertical-align:middle; font-size:30px; top: 30%;\">__DEV_VERSION__</h1>"
  },
  {
   "title": "License Status",
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 0 },
   "content": "<table style=\"height:80%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"home_lic_state\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var state = `${lic_status}`;\n  state = state.toLowerCase();\n  var l_color = \"#299c46\";\n  if (state == \"not activated\") {\n    l_color = \"#ed8128\";\n  }\n  else if (state == \"invalid\" || state == \"no keycode\" || state == \"expired\" || state == \"invalid\") {\n    l_color = \"#d44a3a\";\n  }\n  document.getElementById('home_lic_state').innerHTML = `${lic_status}`;\n  document.getElementById('home_lic_state').style.color = l_color;\n</script>\n<style>\ndiv.submenu-controls > div:nth-child(7) .template-variable, div.submenu-controls > div:nth-child(8) .template-variable {\n  color: #56ce84;\n}\n</style>"
  },
  {
   "title": "License Expiration Time",
   "type": "text",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 2 },
   "content": "<table style=\"height:80%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"home_lic_expired_time\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var lic_e_t = parseInt(`${lic_expired_time}`);\n  var lic_e_t_dis = '';\n  if (lic_e_t == 0 || lic_e_t == '') {\n    lic_e_t_dis = 'N/A';\n  }\n  else {\n    var date_t = new Date(lic_e_t);\n    lic_e_t_dis = date_t.getFullYear() + '-' + (\"0\" + (date_t.getMonth() + 1)).slice(-2) + '-' + (\"0\" + date_t.getDate()).slice(-2) + ' ' + (\"0\" + date_t.getHours()).slice(-2) + ':' + (\"0\" + date_t.getMinutes()).slice(-2) + ':' + (\"0\" + date_t.getSeconds()).slice(-2);\n  }\n  document.getElementById('home_lic_expired_time').innerHTML = lic_e_t_dis;\n</script>"
  },
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\"} == 1)"
    }
   ]
  },
  {
   "title": "Crashing Pods",
   "type": "singlestat",
   "description": "Crashing Pods in cluster (include the control plane)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Nodes UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "min",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubelet\"} == 1) / count(up{job=\"kubelet\"})) * 100"
    }
   ]
  },
  {
   "title": "Nodes Ready",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) / sum(kube_node_status_condition{condition=\"Ready\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}) / sum(kube_node_status_condition{condition=\"MemoryPressure\"}) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}) / sum(kube_node_status_condition{condition=\"DiskPressure\"}) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\"} == 1",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "node:node_cpu_utilisation:avg1m * node:node_num_cpu:sum / scalar(sum(node:node_num_cpu:sum))"
    },
    {
     "expr": "node:node_memory_utilisation:ratio * 1"
    }
   ]
  },
  { "title": "Managed Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Scaler",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select enable_HPA, enable_VPA from alameda_cluster_status..container group by alameda_scaler_name, alameda_scaler_namespace limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(pod_phase) as pod_count  from alameda_cluster_status..container group by  alameda_scaler_name, alameda_scaler_namespace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Resource Usage and Prediction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Application Name",
   "type": "singlestat",
   "description": "Change Application by the Application selector on the top",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select alameda_scaler_name,enable_VPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" =~ /^[[ns]]$/ and \"alameda_scaler_name\" = '$scaler'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU: Observation, and Prediction (in CPU milicore)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(1000 * max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$ns\",pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "alias": "Prediction: CPU usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value)  from \"alameda_prediction\"..\"container\" where  kind = 'raw' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage'  and \"name\" =~ /^[[container]]$/ and \"pod_name\" =~ /^[[pod]]$/ and \"namespace\" =~ /^[[ns]]$/ and time >= now() -2d and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory: Observation, and Prediction",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_usage_bytes{namespace=~\"$ns\",pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"\"}[3600s]))",
     "legendFormat": "Observation: memory usage"
    },
    {
     "alias": "Prediction: memory usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value)  from \"alameda_prediction\"..\"container\" where  kind = 'raw' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and \"name\" =~ /^[[container]]$/ and \"pod_name\" =~ /^[[pod]]$/ and \"namespace\" =~ /^[[ns]]$/ and time >= now() -2d and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Filter",
   "type": "text",
   "description": "Change Filter by the Event-Level selector on the top",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 32 },
   "content": "<table class=\"table\" style=\"overflow: hidden\">\n  <tr style=\"border-top: 2px solid #171819 !important; border-bottom: 2px solid #171819 !important; padding: unset !important; line-height:0.5\">\n    <th class=\"th\" style=\"color: #56ce84\">Level</th>\n    <th class=\"th\" style=\"color: #56ce84\">Namespace</th>\n    <th class=\"th\">Time Range</th>\n  </tr>\n  <tr>\n    <td id=\"event_level\" class=\"td\" style=\"border-bottom: 2px solid #171819 !important;border-right: 2px solid #171819 !important;\"></td>\n    <td id=\"event_namespace\" class=\"td\" style=\"border-bottom: 2px solid #171819 !important;border-right: 2px solid #171819 !important;\"></td>\n    <td id=\"event_tr\" class=\"td\" style=\"border-bottom: 2px solid #171819 !important;border-right: 2px solid #171819 !important;\"></td>\n  </tr>\n</table>\n<script>\n\n  function getTimeRange() {\n    var tr = $(\"span[ng-bind='ctrl.rangeString'\").text();\n    console.log('aa: ', tr);\n    document.getElementById('event_tr').innerHTML = tr;\n  }\n  getTimeRange();\n  $(\"span[ng-bind='ctrl.rangeString'\").on('DOMSubtreeModified', getTimeRange);\n  var event_level = `${event_level}`;\n  var event_namespace = `${event_ns}`;\n  event_namespace = event_namespace.replace('{','');\n  event_namespace = event_namespace.replace('}','');\n  document.getElementById('event_level').innerHTML = event_level;\n  document.getElementById('event_namespace').innerHTML = event_namespace;\n</script>\n<style>\n  .table {\n    border-collapse: collapse;\n    width: 100%;\n    height:95%;\n  }\n  \n  .th {\n    color: #33b5e5;\n    font-size: 13px;\n    text-align: left;\n  }\n  \n  .td {\n    text-align: left;\n    font-size: 13px;\n  }\n</style>"
  },
  {
   "title": "Fatal",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 32 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"fatal_count\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var count = `${fatal_count}` || 0;\n  document.getElementById('fatal_count').style.color = 'red';\n  document.getElementById('fatal_count').innerHTML = count;\n</script>"
  },
  {
   "title": "Error",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 32 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"error_count\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var count = `${error_count}` || 0;\n  document.getElementById('error_count').style.color = 'red';\n  document.getElementById('error_count').innerHTML = count;\n</script>"
  },
  {
   "title": "Warning",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 32 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"warning_count\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var count = `${warning_count}` || 0;\n  document.getElementById('warning_count').style.color = 'yellow';\n  document.getElementById('warning_count').innerHTML = count;\n</script>"
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 32 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"info_count\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var count = `${info_count}` || 0;\n  document.getElementById('info_count').innerHTML = count;\n</script>"
  },
  {
   "title": "Debug",
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 32 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"debug_count\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var count = `${debug_count}` || 0; \n  document.getElementById('debug_count').innerHTML = count;\n</script>\n<style scope>\n .markdown-html td, .markdown-html table, .markdown-html tr {\n  border: none !important\n}\n</style>"
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select * from(select level, subject_kind, subject_name, subject_namespace, message, type from alameda_event..event where level =~ /^[[debug_condition]]$/ and subject_namespace =~ /^[[event_ns]]$/ and 'Debug' = '$event_level'),\n(select level, subject_kind, subject_name, subject_namespace, message, type from alameda_event..event where level =~ /^[[info_condition]]$/ and subject_namespace =~ /^[[event_ns]]$/ and 'Info' = '$event_level'),\n(select level, subject_kind, subject_name, subject_namespace, message, type from alameda_event..event where level =~ /^[[warning_condition]]$/ and subject_namespace =~ /^[[event_ns]]$/ and 'Warning' = '$event_level'),\n(select level, subject_kind, subject_name, subject_namespace, message, type from alameda_event..event where level =~ /^[[error_condition]]$/ and subject_namespace =~ /^[[event_ns]]$/ and 'Error' = '$event_level'),\n(select level, subject_kind, subject_name, subject_namespace, message, type from alameda_event..event where level = 'EVENT_LEVEL_FATAL'  and subject_namespace =~ /^[[event_ns]]$/ and 'Fatal' = '$event_level') where $timeFilter order by time desc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}