{
 "title": "Cluster GPU Insight",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "memory_utilization",
    "label": "Low Memory Utilization Threshold",
    "query": "0.3"
   },
   { "name": "gpu_utilization", "label": "Low GPU Utilization Threshold", "query": "0.3" },
   {
    "name": "high_memory_utilization",
    "label": "High Memory Utilization Threshold",
    "query": "0.8"
   },
   {
    "name": "high_gpu_utilization",
    "label": "High GPU Cycle Utilization Threshold",
    "query": "0.8"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total GPU Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_num_devices)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"alameda_gpu\"..\"nvidia_gpu_num_devices\" where $timeFilter group by time(1s) fill(none) order by time desc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall GPU Cycle Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(nvidia_gpu_duty_cycle)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(value) FROM \"alameda_gpu\"..\"nvidia_gpu_duty_cycle\" where $timeFilter group by time($interval) fill(none) order by time desc /*limit 1*/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall GPU Memory Utilization",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_used_bytes) / sum(nvidia_gpu_memory_total_bytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) * 100 from alameda_gpu..overall_gpu_memory_utilizatin where $timeFilter group by time($interval) fill(none) order by time desc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total GPU Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_total_bytes)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(value) FROM \"alameda_gpu\"..\"nvidia_gpu_memory_total_bytes\" where $timeFilter group by time(1s) fill(none) order by time desc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Low GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Nodes of Low GPU Memory Utilization (<$memory_utilization)",
   "type": "singlestat",
   "description": "The count of nodes that used less than $memory_utilization  of memory",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(nvidia_gpu_memory_used_bytes) by (host) / sum(nvidia_gpu_memory_total_bytes) by (host) <= $memory_utilization)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(host) from (select last(value) as value from alameda_gpu..nodes_of_gpu_memory_utilization where $timeFilter group by host) where value <= $memory_utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Low GPU Memory Utilization (<$memory_utilization)",
   "type": "table",
   "description": "Low GPU memory utilization smaller than (<$memory_utilization)",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_used_bytes) by (host) / sum(nvidia_gpu_memory_total_bytes) by (host) <= $memory_utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select host, value from (select last(value) as value from alameda_gpu..nodes_of_gpu_memory_utilization where $timeFilter group by host) where value <= $memory_utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Nodes with Low GPU Memory Utilization (<$memory_utilization)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Number of nodes" }
   ],
   "targets": [
    {
     "alias": "Number of Nodes",
     "expr": "count(sum(nvidia_gpu_memory_used_bytes) by (host) / sum(nvidia_gpu_memory_total_bytes) by (host) <= $memory_utilization)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Number of nodes",
     "query": "select * from (select count(host) from (select mean(value) as value from alameda_gpu..nodes_of_gpu_memory_utilization where $timeFilter group by host, time(30s)) where value <= $memory_utilization group by time(30s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes of Low GPU Cycle Utilization (<$gpu_utilization)",
   "type": "singlestat",
   "description": "The count of nodes that used less than $gpu_utilization of GPU cycles",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg(nvidia_gpu_duty_cycle) by (host) <= $gpu_utilization)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count from (select count(avg) from (select mean(value) as avg from \"alameda_gpu\"..\"nvidia_gpu_duty_cycle\" where $timeFilter group by host, time($interval) fill(none)) where avg <= $gpu_utilization group by time($interval) ) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Low GPU Cycle Utilization (< $gpu_utilization)",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 15 },
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "avg(nvidia_gpu_duty_cycle / 100) by (host) < $gpu_utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select host, avg from (select last(avg) as avg from (select mean(value)/100 as avg from \"alameda_gpu\"..\"nvidia_gpu_duty_cycle\" where $timeFilter group by host, time($interval) fill(-1)) where avg <> -0.01 group by host) where avg < $gpu_utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Nodes with Low GPU Cycle Utilization (<$gpu_utilization)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Number of nodes" }
   ],
   "targets": [
    {
     "alias": "Number of Nodes",
     "expr": "count(avg(nvidia_gpu_duty_cycle) by (host) <= $gpu_utilization)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Number of nodes",
     "query": "select count from (select count(avg) from (select mean(value) as avg from \"alameda_gpu\"..\"nvidia_gpu_duty_cycle\" where $timeFilter group by host, time($interval) fill(none)) where avg <= $gpu_utilization group by time($interval) ) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "High GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Nodes of High GPU Memory Utilization (>$high_memory_utilization)",
   "type": "singlestat",
   "description": "The count of nodes that used more than $high_memory_utilization  of memory",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 23 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum(nvidia_gpu_memory_used_bytes) by (host) / sum(nvidia_gpu_memory_total_bytes) by (host) >= $high_memory_utilization)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(host) from(select last(value) as value from alameda_gpu..nodes_of_gpu_memory_utilization where $timeFilter group by host) where value >= $high_memory_utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "High GPU Memory Utilization (>$high_memory_utilization)",
   "type": "table",
   "description": "High GPU memory utilization larger than (>$high_memory_utilization)",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 23 },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_used_bytes) by (host) / sum(nvidia_gpu_memory_total_bytes) by (host) >= $high_memory_utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select host, value from (select last(value) as value from alameda_gpu..nodes_of_gpu_memory_utilization where $timeFilter group by host) where value >= $high_memory_utilization",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Nodes with High GPU Memory Utilization (>$high_memory_utilization)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none", "label": "Number of nodes" }
   ],
   "targets": [
    {
     "alias": "Number of Nodes",
     "expr": "count(sum(nvidia_gpu_memory_used_bytes) by (host) / sum(nvidia_gpu_memory_total_bytes) by (host) >= $high_memory_utilization)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Number of nodes",
     "query": "select * from (select count(host) from (select mean(value) as value from alameda_gpu..nodes_of_gpu_memory_utilization where $timeFilter group by host, time(30s)) where value >= $high_memory_utilization group by time(30s))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes of High GPU Cycle Utilization (>$high_gpu_utilization)",
   "type": "singlestat",
   "description": "The count of node that used over $high_gpu_utilization GPU Utilization",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 30 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(avg(nvidia_gpu_duty_cycle / 100) by (host) >= $high_gpu_utilization)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count from (select count(avg) from (select mean(value)/100 as avg from \"alameda_gpu\"..\"nvidia_gpu_duty_cycle\" where $timeFilter group by host, time($interval) fill(none)) where avg >= $high_gpu_utilization group by time($interval) ) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "High GPU Cycle Utilization (>$high_gpu_utilization)",
   "type": "table",
   "description": "High GPU cycle utilization larger than (>$high_gpu_utilization)",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 30 },
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "avg(nvidia_gpu_duty_cycle / 100) by (host) > $high_gpu_utilization",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(avg) as avg from (select mean(value)/100 as avg from \"alameda_gpu\"..\"nvidia_gpu_duty_cycle\" where $timeFilter group by host, time($interval)) where avg > $high_gpu_utilization group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Nodes with High GPU Cycle Utilization (>$high_gpu_utilization)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none", "label": "Number of nodes" }
   ],
   "targets": [
    {
     "alias": "Number of Nodes",
     "expr": "count(avg(nvidia_gpu_duty_cycle / 100) by (host) >= $high_gpu_utilization)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Number of nodes",
     "query": "select count from (select count(avg) from (select mean(value)/100 as avg from \"alameda_gpu\"..\"nvidia_gpu_duty_cycle\" where $timeFilter group by host, time($interval) fill(none)) where avg >= $high_gpu_utilization group by time($interval) ) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "POD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "GPU Used for Pod in Node",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 38 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"value\") from alameda_gpu..gpu_counting_k8s where $timeFilter group by time(5m), \"NodeName\"  fill(none) order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}