{
 "title": "Node GPU Prediction",
 "time": { "from": "now-5d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "select host, value from alameda_gpu..nvidia_gpu_num_devices where $timeFilter group by host limit 1"
   },
   {
    "name": "gpuName",
    "label": "GPU Name",
    "query": "select \"name\", value from alameda_gpu..nvidia_gpu_duty_cycle where $timeFilter  and host  =~ /^[[host]]$/  group by \"name\" limit 1"
   },
   {
    "name": "uuid",
    "label": "GPU UUID",
    "query": "select \"uuid\", value from alameda_gpu..nvidia_gpu_duty_cycle where $timeFilter  and host  =~ /^[[host]]$/  group by \"uuid\" limit 1"
   },
   {
    "name": "nodeName",
    "label": "Node Name",
    "query": "SHOW TAG VALUES ON \"alameda_gpu\" FROM \"gpu_counting_k8s\" WITH KEY = \"NodeName\" WHERE \"NodeName\" =~ /^[[host]]$/"
   }
  ]
 },
 "panels": [
  { "title": "GPU Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Allocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "k8s",
     "query": "SELECT value, NodeName as Host, PodImg, ProjCode, ProjCreator, ProjType  FROM alameda_gpu..gpu_counting_k8s WHERE (\"NodeName\" =~ /^$host$/)  AND time > now()-1d group by PodName ORDER BY time DESC limit 1\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ProjCreator", "operator": "=~", "value": "/^$projCreator$/" }
     ]
    }
   ]
  },
  { "title": "Resource Usage(5 days + 1 day)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU: Observation, and Prediction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_uuid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) as value from alameda_gpu..nvidia_gpu_duty_cycle  where host =~ /^[[host]]$/ and time >= now() - 5d and time <= now() + 1d and uuid =~ /^[[uuid]]$/ group by host, uuid, time(3600s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_uuid(prediction)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) as value from alameda_gpu_prediction..nvidia_gpu_duty_cycle  where host =~ /^[[host]]$/ and time >= now() - 5d and time <= now() + 1d and uuid =~ /^[[uuid]]$/ group by host, uuid, time(3600s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory: Observation, and Prediction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_uuid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from alameda_gpu..uuid_of_gpu_memory_utilization  where host =~ /^[[host]]$/ and time >= now() - 5d and time <= now() + 1d and uuid =~ /^[[uuid]]$/  group by host, uuid , time(3600s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_uuid(prediction)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from alameda_gpu_prediction..nvidia_gpu_memory_usage_percentage  where host =~ /^[[host]]$/ and time >= now() - 5d and time <= now() + 1d and uuid =~ /^[[uuid]]$/  group by host, uuid , time(3600s) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}