{
 "title": "Node GPU Insight",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host:",
    "query": "show tag values on alameda_gpu from nvidia_gpu_num_devices with key = \"host\" where $timeFilter"
   },
   {
    "name": "gpuName",
    "label": "GPU Name:",
    "query": "show tag values on alameda_gpu from nvidia_gpu_duty_cycle with key = \"name\" where $timeFilter  and host  =~ /^[[host]]$/  "
   },
   {
    "name": "uuid",
    "label": "UUID:",
    "query": "show tag values on alameda_gpu from nvidia_gpu_duty_cycle with key = \"uuid\" where $timeFilter  and host  =~ /^[[host]]$/"
   },
   {
    "name": "nodeName",
    "label": "Node Name:",
    "query": "SHOW TAG VALUES ON \"alameda_gpu\" FROM \"gpu_counting_k8s\" WITH KEY = \"NodeName\" WHERE \"NodeName\" =~ /^[[host]]$/"
   },
   {
    "name": "projCreator",
    "label": "Proj Creator:",
    "query": "SHOW TAG VALUES ON \"alameda_gpu\" FROM \"gpu_counting_k8s\" WITH KEY = \"ProjCreator\" WHERE \"NodeName\" =~ /^[[nodeName]]$/"
   },
   {
    "name": "projCode",
    "label": "Proj Code:",
    "query": "SHOW TAG VALUES ON \"alameda_gpu\" FROM \"gpu_counting_k8s\" WITH KEY = \"ProjCode\" WHERE \"NodeName\" =~ /^$nodeName$/ AND \"ProjCreator\" =~ /^$projCreator/"
   },
   {
    "name": "projType",
    "label": "Proj Type:",
    "query": "SHOW TAG VALUES ON \"alameda_gpu\" FROM \"gpu_counting_k8s\" WITH KEY = \"ProjType\" WHERE \"NodeName\" =~ /^$nodeName$/ AND \"ProjCreator\" =~ /^$projCreator/"
   },
   {
    "name": "podName",
    "label": "PodName",
    "query": "SHOW TAG VALUES ON \"alameda_gpu\" FROM \"gpu_counting_k8s\" WITH KEY = \"PodName\" WHERE \"NodeName\" =~ /^$nodeName$/ AND \"ProjCreator\" =~ /^$projCreator/ AND \"ProjCode\" =~ /^$projCode/"
   },
   {
    "name": "podImg",
    "label": "Pod Img:",
    "query": "SHOW TAG VALUES ON \"alameda_gpu\" FROM \"gpu_counting_k8s\" WITH KEY = \"PodImg\" WHERE \"NodeName\" =~ /^$nodeName$/ AND \"ProjCreator\" =~ /^$projCreator/ AND \"ProjCode\" =~ /^$projCode/"
   },
   {
    "name": "issueNode",
    "label": "Issue Node:",
    "query": "Pod_NoWorkLoad :, gn0101.twcc.ai, gn0102.twcc.ai, gn0104.twcc.ai, gn0105.twcc.ai, gn0106.twcc.ai, gn0108.twcc.ai, gn0111.twcc.ai, gn0113.twcc.ai, gn0114.twcc.ai, gn0115.twcc.ai, gn0116.twcc.ai, NoPod_WorkLoad :, gn0107.twcc.ai, gn0109.twcc.ai, gn0110.twcc.ai, gn0112.twcc.ai,"
   }
  ]
 },
 "panels": [
  { "title": "GPU Allocation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Allocation",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "k8s",
     "query": "SELECT value, NodeName, PodName, PodImg, ProjCode, ProjCreator, ProjType  FROM alameda_gpu..gpu_counting_k8s WHERE (\"NodeName\" =~ /^$nodeName$/) AND (\"ProjCreator\" =~ /^$projCreator$/) AND (\"ProjCode\" =~ /^$projCode$/) AND (\"ProjType\" =~ /^$projType$/) AND (\"PodName\" =~ /^$podName$/) AND (\"PodImg\" =~ /^$podImg$/) AND time > now()-1d group by PodName ORDER BY time DESC limit 1\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ProjCreator", "operator": "=~", "value": "/^$projCreator$/" }
     ]
    }
   ]
  },
  { "title": "Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_uuid",
     "expr": "nvidia_gpu_duty_cycle{host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " gpu{{minor_number}}",
     "query": "select mean(value) as value from alameda_gpu..nvidia_gpu_duty_cycle  where host =~ /^[[host]]$/ and $timeFilter group by host, uuid, time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_uuid",
     "expr": "select mean(value) from alameda_gpu..nvidia_gpu_memory_used_bytes where host =~ /^[[host]]$/ and $timeFilter group by host, uuid, time(30s) fill(none) order by time desc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select mean(value) from alameda_gpu..uuid_of_gpu_memory_utilization  where host =~ /^[[host]]$/ and $timeFilter group by host, uuid , time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_uuid",
     "expr": "nvidia_gpu_temperature_celsius{host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " gpu{{minor_number}}",
     "query": "select mean(value) from alameda_gpu..nvidia_gpu_temperature_celsius  where host =~ /^[[host]]$/ and $timeFilter group by host, uuid , time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "alias": "$tag_uuid",
     "expr": "nvidia_gpu_power_usage_milliwatts{host=~\"$host\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": " gpu{{minor_number}}",
     "query": "select mean(value) from alameda_gpu..nvidia_gpu_power_usage_milliwatts  where host =~ /^[[host]]$/ and $timeFilter group by host, uuid, time($interval) fill(previous)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}