// +build !ignore_autogenerated

/*
Copyright 2019 The Alameda Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// autogenerated by controller-gen object, do not modify manually

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlamedaNotificationChannel) DeepCopyInto(out *AlamedaNotificationChannel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlamedaNotificationChannel.
func (in *AlamedaNotificationChannel) DeepCopy() *AlamedaNotificationChannel {
	if in == nil {
		return nil
	}
	out := new(AlamedaNotificationChannel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlamedaNotificationChannel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlamedaNotificationChannelList) DeepCopyInto(out *AlamedaNotificationChannelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlamedaNotificationChannel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlamedaNotificationChannelList.
func (in *AlamedaNotificationChannelList) DeepCopy() *AlamedaNotificationChannelList {
	if in == nil {
		return nil
	}
	out := new(AlamedaNotificationChannelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlamedaNotificationChannelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlamedaNotificationChannelSpec) DeepCopyInto(out *AlamedaNotificationChannelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlamedaNotificationChannelSpec.
func (in *AlamedaNotificationChannelSpec) DeepCopy() *AlamedaNotificationChannelSpec {
	if in == nil {
		return nil
	}
	out := new(AlamedaNotificationChannelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlamedaNotificationChannelStatus) DeepCopyInto(out *AlamedaNotificationChannelStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlamedaNotificationChannelStatus.
func (in *AlamedaNotificationChannelStatus) DeepCopy() *AlamedaNotificationChannelStatus {
	if in == nil {
		return nil
	}
	out := new(AlamedaNotificationChannelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlamedaNotificationTopic) DeepCopyInto(out *AlamedaNotificationTopic) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlamedaNotificationTopic.
func (in *AlamedaNotificationTopic) DeepCopy() *AlamedaNotificationTopic {
	if in == nil {
		return nil
	}
	out := new(AlamedaNotificationTopic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlamedaNotificationTopic) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlamedaNotificationTopicList) DeepCopyInto(out *AlamedaNotificationTopicList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlamedaNotificationTopic, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlamedaNotificationTopicList.
func (in *AlamedaNotificationTopicList) DeepCopy() *AlamedaNotificationTopicList {
	if in == nil {
		return nil
	}
	out := new(AlamedaNotificationTopicList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlamedaNotificationTopicList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlamedaNotificationTopicSpec) DeepCopyInto(out *AlamedaNotificationTopicSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlamedaNotificationTopicSpec.
func (in *AlamedaNotificationTopicSpec) DeepCopy() *AlamedaNotificationTopicSpec {
	if in == nil {
		return nil
	}
	out := new(AlamedaNotificationTopicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlamedaNotificationTopicStatus) DeepCopyInto(out *AlamedaNotificationTopicStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlamedaNotificationTopicStatus.
func (in *AlamedaNotificationTopicStatus) DeepCopy() *AlamedaNotificationTopicStatus {
	if in == nil {
		return nil
	}
	out := new(AlamedaNotificationTopicStatus)
	in.DeepCopyInto(out)
	return out
}
