{
 "title": "ProphetStor",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kube_node_labels, label_kubernetes_io_hostname)"
   },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "show tag values on alameda_cluster_status from container with key=\"alameda_scaler_namespace\""
   },
   {
    "name": "scaler",
    "label": "AlamedaScaler",
    "query": "select alameda_scaler_name,enable_VPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" =~ /^[[ns]]$/"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "select pod_name, enable_VPA from alameda_cluster_status..container where \"alameda_scaler_namespace\"=~ /^[[ns]]$/ and \"alameda_scaler_name\" =~ /^[[scaler]]$/"
   },
   {
    "name": "container",
    "label": "container",
    "query": "select \"name\", enable_VPA from alameda_cluster_status..container where \"alameda_scaler_namespace\"=~ /^[[ns]]$/ and \"alameda_scaler_name\" =~ /^[[scaler]]$/"
   },
   {
    "name": "s_scaler",
    "label": "Scaler",
    "query": "select alameda_scaler_name,enable_VPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" =~ /^[[ns]]$/"
   },
   {
    "name": "s_pod",
    "query": "select pod_name, enable_VPA from alameda_cluster_status..container where \"alameda_scaler_name\" = '$s_scaler'"
   },
   {
    "name": "s_container",
    "query": "select \"name\", enable_VPA from alameda_cluster_status..container where \"alameda_scaler_name\" = '$s_scaler'"
   }
  ]
 },
 "panels": [
  { "title": "ProphetStor Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Product",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 1 },
   "content": "<div>\n  <img style=\"vertical-align:middle\" src=\"https://i1.wp.com/www.prophetstor.com/wp-content/uploads/2017/05/prophetstor_white_logo.png?fit=143%2C62&ssl=1\">\n  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\n  <span style=\"vertical-align:middle; font-size:30px\">Federator.ai</span>\n</div\n"
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 13, "y": 1 },
   "content": "<h1 style=\"position: relative; text-align: center; vertical-align:middle; font-size:30px; top: 30%;\">1.0.0</h1>"
  },
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"kubelet\"})"
    }
   ]
  },
  {
   "title": "Crashing Pods",
   "type": "singlestat",
   "description": "Crashing Pods in cluster (include the control plane)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[1h]) > 5)"
    }
   ]
  },
  {
   "title": "Nodes UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "min",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubelet\"} == 1) / count(up{job=\"kubelet\"})) * 100"
    }
   ]
  },
  {
   "title": "Node Ready",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "format": "percent",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) / sum(kube_node_status_condition{condition=\"Ready\"}) * 100"
    }
   ]
  },
  {
   "title": "Node Memory Pressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}) / sum(kube_node_status_condition{condition=\"MemoryPressure\"}) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Node Disk Pressure",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}) / sum(kube_node_status_condition{condition=\"DiskPressure\"}) * 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\"} == 1",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "node:node_cpu_utilisation:avg1m * node:node_num_cpu:sum / scalar(sum(node:node_num_cpu:sum))"
    },
    {
     "expr": "node:node_memory_utilisation:ratio * 1"
    }
   ]
  },
  { "title": "Managed Pod Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Scaler",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select enable_HPA, enable_VPA from alameda_cluster_status..container group by alameda_scaler_name, alameda_scaler_namespace limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select count(pod_phase) as pod_count  from alameda_cluster_status..container group by  alameda_scaler_name, alameda_scaler_namespace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Usage and Recommendation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "CPU: Observation, Prediction, and Recommendation (in CPU milicore)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(1000 * max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{pod_name=~\"$s_pod\", container_name=~\"$s_container\", container_name!=\"\"}[3600s]))",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "alias": "Prediction: CPU usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value)  from \"alameda_prediction\"..\"container\" where  kind = 'raw' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage'  and \"pod_name\" =~ /^[[s_pod]]$/ and time >= now() -2d and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: CPU usage upperbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) from \"alameda_prediction\"..\"container\" where  kind = 'upper_bound' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage' and \"name\" =~ /^[[s_container]]$/ and \"pod_name\" =~ /^[[s_pod]]$/ and time >= now() and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: CPU usage lowerbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) from \"alameda_prediction\"..\"container\" where  kind = 'lower_bound' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage' and \"name\" =~ /^[[s_container]]$/ and \"pod_name\" =~ /^[[s_pod]]$/ and time >= now() and time <= now() + 1d  group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory: Observation, Prediction, and Recommendation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_usage_bytes{pod_name=~\"$s_pod\", container_name=~\"$s_container\", container_name!=\"\"}[3600s]))",
     "legendFormat": "Observation: memory usage"
    },
    {
     "alias": "Prediction: memory usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value)  from \"alameda_prediction\"..\"container\" where  kind = 'raw' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and \"pod_name\" =~ /^[[s_pod]]$/ and time >= now() -2d and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: memory usage upperbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) from \"alameda_prediction\"..\"container\" where  kind = 'upper_bound' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and \"name\" =~ /^[[s_container]]$/ and \"pod_name\" =~ /^[[s_pod]]$/ and time >= now() and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: memory usage lowerbound",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) from \"alameda_prediction\"..\"container\" where  kind = 'lower_bound' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and \"name\" =~ /^[[s_container]]$/ and \"pod_name\" =~ /^[[s_pod]]$/ and time >= now() and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}