apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-executor
  name: alameda-executor
  namespace: alameda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: alameda-executor
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alameda
        component: alameda-executor
    spec:
      containers:
      - image: quay.io/prophetstor/alameda-executor-ubi:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/federatorai-executor
            - probe
            - --type=liveness
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: executor
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/federatorai-executor
            - probe
            - --type=readiness
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alameda/federatorai-execution/config.yml
          name: alameda-executor
          subPath: config.yml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alameda-executor
      serviceAccountName: alameda-executor
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: alameda-executor
        name: alameda-executor
status: {}
