{
 "title": "HPA Recommendation",
 "time": { "from": "now-1h", "to": "now+20m" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "label": "Namespace",
    "query": "select alameda_scaler_namespace,enable_HPA from alameda_cluster_status..container where enable_HPA= true group by \"alameda_scaler_namespace\" order by time desc limit 1"
   },
   {
    "name": "scaler",
    "label": "AlamedaScaler",
    "query": "select alameda_scaler_name,enable_HPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" = '$ns' and enable_HPA= true group by \"alameda_scaler_namespace\", \"alameda_scaler_name\" order by time desc limit 1"
   },
   {
    "name": "controller",
    "label": "controller",
    "query": "show tag values on alameda_cluster_status from controller with key=\"name\" where \"owner_namespace\" = '$ns' and \"owner_name\" = '$scaler'"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "select pod_name,enable_HPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and \"top_controller_name\" = '$controller' group by \"pod_name\" order by time desc limit 1"
   },
   {
    "name": "container",
    "label": "container",
    "query": "select \"name\",enable_HPA from alameda_cluster_status..container where \"alameda_scaler_namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and \"top_controller_name\" = '$controller' group by \"name\" order by time desc limit 1"
   }
  ]
 },
 "panels": [
  { "title": "Managed Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Managed Controllers with HPA ScalingTool per Selected AlamedaScaler",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select top_controller_kind as \"kind\", top_controller_name as \"controller\" from (select * from alameda_cluster_status..container where top_controller_kind = 'StatefulSet' and enable_HPA = true and alameda_scaler_name = '$scaler' limit 1), (select * from alameda_cluster_status..container where top_controller_kind = 'Deployment' and enable_HPA = true and alameda_scaler_name = '$scaler' limit 1), (select * from alameda_cluster_status..container where top_controller_kind = 'DeploymentConfig' and enable_HPA = true and alameda_scaler_name = '$scaler' limit 1) group by alameda_scaler_name, alameda_scaler_namespace",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Controller Resource Usage and Recommendation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Desired replica",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select desired_replicas as \"desired replicas\" from alameda_recommendation..controller where type = 'CRT_Primitive' and namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current replica",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_replicationcontroller_spec_replicas{namespace = \"$ns\", replicationcontroller=~\"$controller.*\" }) or 1-absent(sum(kube_replicationcontroller_spec_replicas{namespace = \"$ns\", replicationcontroller=~\"$controller.*\" }))\n\n+ \n\nsum(kube_replicaset_spec_replicas{namespace = \"$ns\", replicaset=~\"$controller.*\" }) or 1-absent(sum(kube_replicaset_spec_replicas{namespace = \"$ns\", replicaset=~\"$controller.*\" }))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select current_replicas as \"current replicas\" from alameda_recommendation..controller where namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total CPU limit (milicore)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1000 * sum(sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$ns\", pod=~\"$controller.*\"}) by (namespace, pod) * sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$ns\", pod=~\"$controller.*\"}) by (namespace, pod))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select current_cpu_limits from alameda_recommendation..controller where namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1\n\nsum(label_replace(\nsum(avg_over_time(kube_pod_container_resource_limits_cpu_cores{container!=\"\",container!=\"POD\",node=\"$node\"}[10m])) by (pod), \n\"pod_name\",\"$1\",\"pod\",\"(.+)\")\nor up * 0\n) by (pod_name)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total CPU request (milicore)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "1000 * sum(sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$ns\", pod=~\"$controller.*\"}) by (namespace, pod) * sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$ns\", pod=~\"$controller.*\"}) by (namespace, pod))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "1000 * sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$ns\", pod=~\"$controller.*\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total memory limit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$ns\", pod=~\"$controller.*\"}) by (namespace, pod) * sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$ns\", pod=~\"$controller.*\"}) by (namespace, pod))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select current_mem_limits from alameda_recommendation..controller where namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total memory request",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$ns\", pod=~\"$controller.*\"}) by (namespace, pod) * sum(kube_pod_status_phase{phase=\"Running\", namespace=\"$ns\", pod=~\"$controller.*\"}) by (namespace, pod))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select current_mem_requests from alameda_recommendation..controller where namespace = '$ns' and \"name\" = '$controller' order by time desc limit 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Object CPU Usage(milicore) vs Replica Recommendation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "1000 * sum(max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"$ns\", pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"\"}[30s]))",
     "legendFormat": "Observation : CPU usage"
    },
    {
     "alias": "Recommendation: desired CPU limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select desired_cpu_limits from \"alameda_recommendation\"..\"controller\" where type = 'CRT_Primitive' and \"name\" = '$controller' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Resource Object Memory vs Replica Recommendation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(container_memory_usage_bytes{namespace=\"$ns\", pod_name=~\"$pod\", container_name=~\"$container\", container_name!=\"\"}[30s]))",
     "legendFormat": "Observation : memory usage"
    },
    {
     "alias": "Recommendation : desired memory limit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select desired_mem_limits from \"alameda_recommendation\"..\"controller\" where \"name\" = '$controller' and \"namespace\" = '$ns'  AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}