apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-evictioner
  name: alameda-evictioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alameda-evictioner
subjects:
- kind: ServiceAccount
  name: alameda-evictioner
  namespace: alameda
