apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-evictioner
  name: alameda-evictioner
  namespace: alameda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alameda
      component: alameda-evictioner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alameda
        component: alameda-evictioner
    spec:
      containers:
      - env:
        - name: ALAMEDA_EVICTIONER_DATAHUB_ADDRESS
          value: alameda-datahub.alameda:50050
        - name: ALAMEDA_EVICTIONER_EVICTION_ENABLE
          value: "true"
        image: quay.io/prophetstor/alameda-evictioner-ubi:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/evictioner
            - probe
            - --type=liveness
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: evictioner
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/evictioner
            - probe
            - --type=readiness
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: alameda-evictioner
      serviceAccountName: alameda-evictioner
      terminationGracePeriodSeconds: 30
status: {}
