apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: alameda-rabbitmq
  namespace: alameda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: alameda-rabbitmq
subjects:
- kind: ServiceAccount
  name: alameda-rabbitmq
