apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
    chart: rabbitmq-0.3.0
    heritage: Tiller
    release: alameda
  name: alameda-rabbitmq
  namespace: alameda
