apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rabbitmq
    chart: rabbitmq-0.3.0
    heritage: Tiller
    release: alameda
    type: ClusterIP
  name: alameda-rabbitmq
  namespace: alameda
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: http
    port: 15672
    protocol: TCP
    targetPort: http
  selector:
    app: rabbitmq
    release: alameda
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
