apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recommender.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |-
    [global]
    hpa_interval = 180
    vpa_short_interval = 300
    vpa_long_interval = 3600
    debug = false

    [datahub]
    address = "{{ .Values.global.component.datahub.name }}.{{ .Release.Namespace }}.svc"
    port = {{ .Values.global.component.datahub.service.port }}

    [hpa_scaling]
    alpha = 0.25
    k8s_threshold = 0.8
    limits_threshold = 0.9
    sample_rate = 15
    period_rate = 60
    period_count = 5
    data_source = "workload"
