---
# Source: alameda/charts/notifier/templates/certificate.yaml
#apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: alameda-notifier-serving-cert
  namespace: alameda  
spec:
  commonName: alameda-notifier-webhook-service.alameda.svc
  dnsNames:
  - alameda-notifier-webhook-service.alameda.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: alameda-notifier-selfsigned-issuer
  secretName: alameda-notifier-webhook-server-cert
