apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-notifier
  name: alameda-notifier
  namespace: alameda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alameda
      component: alameda-notifier
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alameda
        component: alameda-notifier
    spec:
      containers:
      - env:
        - name: ALAMEDA_NOTIFIER_DATAHUB_ADDRESS
          value: alameda-datahub.alameda:50050
        - name: ALAMEDA_NOTIFIER_RABBITMQ_URL
          value: amqp://admin:adminpass@alameda-rabbitmq.alameda:5672
        image: quay.io/prophetstor/alameda-notifier-ubi:v4.3.1046
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/notifier
            - --liveness-probe
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: notifier
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/notifier
            - --readiness-probe
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: alameda-notifier-webhook-server-cert
status: {}
