---
# Source: alameda/charts/notifier/templates/issuer.yaml
#apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: alameda-notifier-selfsigned-issuer
  namespace: alameda
spec:
  selfSigned: {}
