apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: alameda-notifier-webhook-service
  namespace: alameda
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 50443
  selector:
    app: alameda
    component: alameda-notifier
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
