apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: alameda-influxdb
    chart: influxdb-1.3.3
    heritage: Tiller
    release: alameda-influxdb
  name: alameda-influxdb
spec:
  ports:
  - name: api
    port: 8086
    protocol: TCP
    targetPort: 8086
  - name: rpc
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: alameda-influxdb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
