{
 "title": "Multi-Cloud Cost Analysis",
 "time": { "from": "now-1h", "to": "now+15m" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "resource", "label": "Scope", "query": "Cluster, Namespace" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "show tag values on alameda_cluster_status from pod with key=\"alameda_scaler_namespace\" where 'Cluster' != '$resource'"
   },
   { "name": "purchase_option", "label": "RI Consideration", "query": "Yes, No" },
   {
    "name": "country",
    "label": "Country",
    "query": "show tag values on alameda_fedemeter from recommendation_jeri with key = \"country\""
   },
   {
    "name": "scaler",
    "label": "Application",
    "query": "show tag values on alameda_cluster_status from pod with key=\"alameda_scaler_name\"  where \"alameda_scaler_namespace\" = '$ns'  and 'Namespace' != '$resource'"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "show tag values on alameda_cluster_status from pod with key=\"pod_name\" where \"alameda_scaler_namespace\" = '$ns' and \"alameda_scaler_name\" = '$scaler' and 'Container' = '$resource'"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "show tag values on alameda_cluster_status from container with key=\"name\" where \"pod_name\" = '$pod' and 'Container' = '$resource'"
   },
   {
    "name": "h_ns",
    "query": "select alameda_scaler_namespace, enable_VPA from (select alameda_scaler_namespace, enable_VPA from alameda_cluster_status..pod where 'Cluster' = '$resource' group by alameda_scaler_namespace),(select alameda_scaler_namespace, enable_VPA from alameda_cluster_status..pod where 'Cluster' != '$resource' and alameda_scaler_namespace = '$ns' group by alameda_scaler_namespace)"
   },
   {
    "name": "h_scaler",
    "query": "select alameda_scaler_name, enable_VPA from ( select alameda_scaler_name, enable_VPA from alameda_cluster_status..pod where \"alameda_scaler_namespace\" =~ /^[[h_ns]]$/  and ('Cluster' = '$resource' or 'Namespace' = '$resource') group by alameda_scaler_name), ( select alameda_scaler_name, enable_VPA from alameda_cluster_status..pod where \"alameda_scaler_namespace\" ='$ns' and 'Cluster' != '$resource' and 'Namespace' != '$resource' group by alameda_scaler_name)"
   },
   {
    "name": "h_pod",
    "query": "select \"name\", enable_VPA from (select \"name\", enable_VPA from alameda_cluster_status..pod where \"alameda_scaler_namespace\"=~ /^[[h_ns]]$/ and \"alameda_scaler_name\" =~ /^[[h_scaler]]$/ and 'Cluster' = '$resource'), (select \"name\", enable_VPA from alameda_cluster_status..pod where \"alameda_scaler_namespace\"= '$ns' and \"alameda_scaler_name\" =~ /^[[h_scaler]]$/ and 'Namespace' = '$resource'), (select \"name\", enable_VPA from alameda_cluster_status..pod where \"alameda_scaler_namespace\"= '$ns' and \"alameda_scaler_name\" ='$scaler' and 'Application' = '$resource'), (select \"name\", enable_VPA from alameda_cluster_status..pod where \"alameda_scaler_namespace\"= '$ns' and \"alameda_scaler_name\" ='$scaler' and \"pod_name\" = '$pod' and 'Container' = '$resource')"
   },
   {
    "name": "h_container",
    "query": "select \"name\", enable_VPA from (select \"name\", enable_VPA from alameda_cluster_status..container where \"pod_name\" =~ /^[[h_pod]]$/ and 'Cluster' = '$resource'), (select \"name\", enable_VPA from alameda_cluster_status..container where \"pod_name\" =~ /^[[h_pod]]$/ and 'Namespace' = '$resource'), (select \"name\", enable_VPA from alameda_cluster_status..container where \"pod_name\" =~ /^[[h_pod]]$/ and 'Application' = '$resource'), (select \"name\", enable_VPA from alameda_cluster_status..container where \"pod_name\" ='$h_pod' and \"name\" = '$container' and 'Container' = '$resource')"
   },
   {
    "name": "aws_stime_month",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'aws'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-2d  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "aws_stime_week",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'aws'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-12h  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "aws_stime_daily",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'aws'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-2h  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "azure_stime_month",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'azure'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-2d  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "azure_stime_week",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'azure'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-12h  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "azure_stime_daily",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'azure'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-2h  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "gcp_stime_month",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'azure'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-2d  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "gcp_stime_week",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'gcp'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-12h  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "gcp_stime_daily",
    "query": "select starttime from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'gcp'  and ((\"reservedinstances\" = '0' and 'No' = '$purchase_option') or (\"reservedinstances\" = '1' and 'Yes' = '$purchase_option')) and time >= now()-2h  and time <= now() and country = '$country' order by time desc limit 1"
   },
   {
    "name": "count_container",
    "query": "select count(uid) from (select uid, resource_request_cpu from (select uid, resource_request_cpu from alameda_cluster_status..container where \"pod_name\" =~ /^[[h_pod]]$/ and ('Cluster' = '$resource' or 'Namespace' = '$resource' or 'Application' = '$resource')), (select uid, resource_request_cpu from alameda_cluster_status..container where \"pod_name\" = '$pod' and 'Container' = '$resource'))"
   },
   {
    "name": "current_provider",
    "query": "select  io_provider  from alameda_cluster_status..node order by time desc limit 1"
   },
   {
    "name": "current_region",
    "query": "select io_region from alameda_cluster_status..node order by time desc limit 1"
   },
   {
    "name": "current_zone",
    "query": "select io_zone from alameda_cluster_status..node order by time desc limit 1"
   },
   {
    "name": "current_cost",
    "query": "select sum(totalcost) as totalcost from alameda_fedemeter..calculate_instance where time >= now() -60m group by time(1s) fill(none) order by time desc limit 1"
   },
   {
    "name": "daily_aws_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'aws' and starttime = '$aws_stime_daily' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "daily_azure_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'azure' and starttime = '$azure_stime_daily' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "daily_gcp_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'gcp' and starttime = '$gcp_stime_daily' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "daily_aws_cost",
    "query": "select sum(totalcost) from alameda_fedemeter..recommendation_jeri  where granularity = '3600' and provider = 'aws' and starttime = '$aws_stime_daily' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option') or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option' )) and country = '$country' "
   },
   {
    "name": "daily_azure_cost",
    "query": "select sum(totalcost) from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'azure' and starttime = '$azure_stime_daily' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' "
   },
   {
    "name": "daily_gcp_cost",
    "query": "select sum(totalcost) from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'gcp' and starttime = '$gcp_stime_daily' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' "
   },
   {
    "name": "weekly_aws_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'aws' and starttime = '$aws_stime_week' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "weekly_azure_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'azure' and starttime = '$azure_stime_week' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "weekly_gcp_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'gcp' and starttime = '$gcp_stime_week' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "weekly_aws_cost",
    "query": "select sum(totalcost) from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'aws' and starttime = '$aws_stime_week' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' "
   },
   {
    "name": "weekly_azure_cost",
    "query": "select sum(totalcost) from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'azure' and starttime = '$azure_stime_week' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' group by time(1s) fill(none) order by time desc limit 1"
   },
   {
    "name": "weekly_gcp_cost",
    "query": "select sum(totalcost) from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'gcp' and starttime = '$gcp_stime_week' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' "
   },
   {
    "name": "monthly_aws_cost",
    "query": "select sum(totalcost) from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'aws' and starttime = '$aws_stime_month' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' "
   },
   {
    "name": "monthly_azure_cost",
    "query": "select  sum(totalcost) from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'azure' and starttime = '$azure_stime_month' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' "
   },
   {
    "name": "monthly_gcp_cost",
    "query": "select sum(totalcost) from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'gcp' and starttime = '$gcp_stime_month' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country'"
   },
   {
    "name": "monthly_aws_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'aws' and starttime = '$aws_stime_month' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "monthly_azure_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'azure' and starttime = '$azure_stime_month' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "monthly_gcp_region",
    "query": "select region from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'gcp' and starttime = '$gcp_stime_month' and ( ( \"reservedinstances\" = '1' and 'Yes' = '$purchase_option')  or ( \"reservedinstances\" = '0' and 'No' = '$purchase_option') ) and country = '$country' order by time desc limit 1"
   },
   {
    "name": "current_cpu_total",
    "query": "select  sum(node_cpu_cores)*10 from alameda_cluster_status..node"
   },
   {
    "name": "current_memory_total",
    "query": "select  sum(node_memory_bytes) from alameda_cluster_status..node"
   }
  ]
 },
 "panels": [
  { "title": "Current Cluster Configuration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <img id=\"config_provider\" style=\"display:block; margin-left:auto; margin-right:auto;\">\n    </td>\n  </tr>\n</table>\n<script>\n  var currentProvider = `${current_provider}`.toLowerCase();\n  if (currentProvider === 'aws') {\n    document.getElementById('config_provider').src = 'https://d1.awsstatic.com/gamedev/gamelift/awshomepage.8845ec5b83a849d57f677cf9010c25abd357ea2e.PNG';\n  } else if ( currentProvider === 'azure') {\n    document.getElementById('config_provider').src = 'https://www.net4all.ch/wp-content/uploads/sites/4/2018/04/azure-logo_200x200.png';\n    document.getElementById('config_provider').style.height = '50%';\n    document.getElementById('config_provider').style.width = '50%';\n  } else if ( currentProvider === 'gcp') {\n    document.getElementById('config_provider').src = 'https://miro.medium.com/max/1200/1*eSQnSxgOwNWtjsnbBl3w4A.png';\n    document.getElementById('config_provider').style.height = '40%';\n  }\n  //document.getElementById('config_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'black'\n</script>"
  },
  {
   "title": "Current Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"config_cost\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px; color:black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var cost = `$${$current_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per month</div>`;\n  document.getElementById('config_cost').innerHTML = cost;\n  document.getElementById('config_cost').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"config_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${current_region}`;\n  document.getElementById('config_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Current Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select  \"name\", io_role, io_instance_type, node_cpu_cores, node_memory_bytes, io_storage_size from alameda_cluster_status..node\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost Analysis for Cloud Services (Daily)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Resource Utilization for Managed Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum( 1000 * max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$h_ns\", pod_name=~\"$h_pod\", container_name=~\"$h_container\", container_name!=\"\"}[3600s])) / $current_cpu_total",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum(max_over_time(container_memory_usage_bytes{namespace=~\"$h_ns\", pod_name=~\"$h_pod\", container_name=~\"$h_container\", container_name!=\"\"}[3600s])) * 100 / $current_memory_total",
     "legendFormat": "Observation: memory usage"
    },
    {
     "alias": "Prediction: CPU usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) / $current_cpu_total from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5d and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: memory usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) * 100 / $current_memory_total from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '3600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5d and time <= now() + 1d group by time(3600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 15 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <img id=\"daily_aws_provider\" style=\"display:block; margin-left:auto; margin-right:auto;\" src=\"https://d1.awsstatic.com/gamedev/gamelift/awshomepage.8845ec5b83a849d57f677cf9010c25abd357ea2e.PNG\">\n    </td>\n  </tr>\n</table>\n<script>\n  //document.getElementById('daily_aws_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 15 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"daily_aws\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;color: black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$daily_aws_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per day</div>`;\n  document.getElementById('daily_aws').innerHTML = price;\n  document.getElementById('daily_aws').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>\n<style>\n .markdown-html table {\n  border: none !important\n}\n .markdown-html tr {\n  border: none !important\n}\n .markdown-html td {\n  border: none !important\n}\n</style>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 15 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"daily_aws_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${daily_aws_region}`;\n  document.getElementById('daily_aws_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'aws'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$aws_stime_daily' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, \"\" as masterrinum, workerondemandnum, \"\" as workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'aws'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$aws_stime_daily' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <img id=\"daily_azure_provider\" style=\"display:block; margin-left:auto; margin-right:auto; width:50%; height:50%\" src=\"https://www.net4all.ch/wp-content/uploads/sites/4/2018/04/azure-logo_200x200.png\">\n    </td>\n  </tr>\n</table>\n<script>\n  //document.getElementById('daily_azure_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 19 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"daily_azure\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;color: black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$daily_azure_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per day</div>`;\n  document.getElementById('daily_azure').innerHTML = price;\n  document.getElementById('daily_azure').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 19 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"daily_azure_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region =  `${daily_azure_region}`;\n  document.getElementById('daily_azure_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 19 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'azure'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$azure_stime_daily' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, \"\" as masterrinum, workerondemandnum, \"\" as workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'azure'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$azure_stime_daily' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n       <img id=\"daily_gcp_provider\" style=\"display:block; margin-left:auto; margin-right:auto;height:25%;\" src=\"https://www.abacoinformatica.com/wp-content/uploads/2019/03/Google-Cloud-Platform.png\">\n    </td>\n  </tr>\n</table>\n<script>\n  //document.getElementById('daily_gcp_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 23 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"daily_gcp\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;color: black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$daily_gcp_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per day</div>`;\n  document.getElementById('daily_gcp').innerHTML = price;\n  document.getElementById('daily_gcp').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 23 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"daily_gcp_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region =  `${daily_gcp_region}`;\n  document.getElementById('daily_gcp_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 23 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'gcp'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$gcp_stime_daily' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, \"\" as masterrinum, workerondemandnum, \"\" as workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '3600' and provider = 'gcp'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$gcp_stime_daily' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost Analysis for Cloud Services (Weekly)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Resource Utilization for Managed Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum( 1000 * max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$h_ns\", pod_name=~\"$h_pod\", container_name=~\"$h_container\", container_name!=\"\"}[21600s])) / $current_cpu_total",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum(max_over_time(container_memory_usage_bytes{namespace=~\"$h_ns\", pod_name=~\"$h_pod\", container_name=~\"$h_container\", container_name!=\"\"}[21600s])) * 100 / $current_memory_total",
     "legendFormat": "Observation: memory usage"
    },
    {
     "alias": "Prediction: CPU usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) / $current_cpu_total from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 5w and time <= now() + 1w group by time(21600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: memory usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) * 100 / $current_memory_total from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '21600' and \"metric\" = 'memory_usage_bytes' and time >= now() - 5w and time <= now() + 1w group by time(21600s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <img id=\"weekly_aws_provider\" style=\"display:block; margin-left:auto; margin-right:auto;\" src=\"https://d1.awsstatic.com/gamedev/gamelift/awshomepage.8845ec5b83a849d57f677cf9010c25abd357ea2e.PNG\">\n    </td>\n  </tr>\n</table>\n<script>\n  //document.getElementById('weekly_aws_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 37 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"weekly_aws\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;color: black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$weekly_aws_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per week</div>`;\n  document.getElementById('weekly_aws').innerHTML = price;\n  document.getElementById('weekly_aws').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>\n<style>\n .markdown-html table {\n  border: none !important\n}\n .markdown-html tr {\n  border: none !important\n}\n .markdown-html td {\n  border: none !important\n}\n</style>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 37 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"weekly_aws_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${weekly_aws_region}`;\n  document.getElementById('weekly_aws_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 37 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'aws'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$aws_stime_week' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, \"\" as masterrinum, workerondemandnum, \"\" as workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'aws'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$aws_stime_week' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 41 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n     <img id=\"weekly_azure_provider\" style=\"display:block; margin-left:auto; margin-right:auto; width:50%; height:50%\" src=\"https://www.net4all.ch/wp-content/uploads/sites/4/2018/04/azure-logo_200x200.png\">\n    </td>\n  </tr>\n</table>\n<script>\n  //document.getElementById('weekly_azure_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 41 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"weekly_azure\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;color: black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$weekly_azure_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per week</div>`;\n  document.getElementById('weekly_azure').innerHTML = price;\n  document.getElementById('weekly_azure').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 41 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"weekly_azure_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${weekly_azure_region}`;\n  document.getElementById('weekly_azure_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 41 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'azure'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$azure_stime_week' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, \"\" as masterrinum, workerondemandnum, \"\" as workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'azure'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$azure_stime_week' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 45 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n     <img id=\"weekly_gcp_provider\" style=\"display:block; margin-left:auto; margin-right:auto;height:25%;\" src=\"https://www.abacoinformatica.com/wp-content/uploads/2019/03/Google-Cloud-Platform.png\">\n    </td>\n  </tr>\n</table>\n<script>\n  //document.getElementById('weekly_gcp_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 45 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"weekly_gcp\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;color: black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$weekly_gcp_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per week</div>`;\n  document.getElementById('weekly_gcp').innerHTML = price;\n  document.getElementById('weekly_gcp').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 45 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"weekly_gcp_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${weekly_gcp_region}`;\n  document.getElementById('weekly_gcp_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 45 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'gcp'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$gcp_stime_week' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, \"\" as masterrinum, workerondemandnum, \"\" as workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '21600' and provider = 'gcp'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$gcp_stime_week' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost Analysis for Cloud Services (Monthly)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "Resource Utilization for Managed Pods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum( 1000 * max_over_time(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$h_ns\", pod_name=~\"$h_pod\", container_name=~\"$h_container\", container_name!=\"\"}[86400s])) / $current_cpu_total",
     "legendFormat": "Observation : CPU Usage"
    },
    {
     "expr": "sum(max_over_time(container_memory_usage_bytes{namespace=~\"$h_ns\", pod_name=~\"$h_pod\", container_name=~\"$h_container\", container_name!=\"\"}[86400s])) * 100 / $current_memory_total",
     "legendFormat": "Observation: memory usage"
    },
    {
     "alias": "Prediction: CPU usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) / $current_cpu_total from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'cpu_usage_seconds_percentage' and time >= now() - 20w and time <= now() + 4w group by time(86400s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Prediction: memory usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(value) * 100 / $current_memory_total from \"alameda_prediction\"..\"cluster\" where kind = 'raw' and granularity = '86400' and \"metric\" = 'memory_usage_bytes' and time >= now() - 20w and time <= now() + 4w group by time(86400s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 59 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <img id=\"monthly_aws_provider\" style=\"display:block; margin-left:auto; margin-right:auto;\" src=\"https://d1.awsstatic.com/gamedev/gamelift/awshomepage.8845ec5b83a849d57f677cf9010c25abd357ea2e.PNG\">\n    </td>\n  </tr>\n</table>\n<script>\n  //document.getElementById('monthly_aws_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 59 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"monthly_aws\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px; color:black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$monthly_aws_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per month</div>`;\n  document.getElementById('monthly_aws').innerHTML = price;\n  document.getElementById('monthly_aws').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>\n<style>\n .markdown-html table {\n  border: none !important\n}\n .markdown-html tr {\n  border: none !important\n}\n .markdown-html td {\n  border: none !important\n}\n</style>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 59 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"monthly_aws_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${monthly_aws_region}`;\n  document.getElementById('monthly_aws_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 59 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'aws'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$aws_stime_month' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, \"\" as masterrinum, workerondemandnum, \"\" as workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'aws'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$aws_stime_month' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 63 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <img id=\"monthly_azure_provider\" style=\"display:block; margin-left:auto; margin-right:auto; width:50%; height:50%\" src=\"https://www.net4all.ch/wp-content/uploads/sites/4/2018/04/azure-logo_200x200.png\">\n    </td>\n  </tr>\n</table>\n<script>\n  //document.getElementById('monthly_azure_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 63 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"monthly_azure\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px;color:black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$monthly_azure_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per month</div>`;\n  document.getElementById('monthly_azure').innerHTML = price;\n  document.getElementById('monthly_azure').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 63 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"monthly_azure_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${monthly_azure_region}`;\n  document.getElementById('monthly_azure_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 63 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'azure'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$azure_stime_month' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'azure'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$azure_stime_month' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recommended Provider",
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 67 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <img id=\"monthly_gcp_provider\" style=\"display:block; margin-left:auto; margin-right:auto;height:25%;\" src=\"https://www.abacoinformatica.com/wp-content/uploads/2019/03/Google-Cloud-Platform.png\">\n    </td>\n  </tr>\n</table>\n<script>\n  // https://miro.medium.com/max/1200/1*eSQnSxgOwNWtjsnbBl3w4A.png\n  //document.getElementById('monthly_gcp_provider').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'darkgoldenrod'\n</script>"
  },
  {
   "title": "Estimated Cost",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 67 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"monthly_gcp\" type=\"text/JavaScript\" style=\"text-align:center;font-size:30px; color: black\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var price = `$${$monthly_gcp_cost.toFixed(2)}<div style=\"font-size:18px; color:black\">per month</div>`;\n  document.getElementById('monthly_gcp').innerHTML = price;\n  document.getElementById('monthly_gcp').parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.parentElement.style.backgroundColor = 'cadetblue'\n</script>"
  },
  {
   "title": "Region",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 67 },
   "content": "<table style=\"height:100%;width:100%\">\n  <tr>\n    <td>\n      <div id=\"monthly_gcp_region\" type=\"text/JavaScript\" style=\"text-align:center;font-size:20px\"></div>\n    </td>\n  </tr>\n</table>\n<script>\n  var region = `${monthly_gcp_region}`;\n  document.getElementById('monthly_gcp_region').innerHTML = region;\n</script>"
  },
  {
   "title": "Cluster Configuration",
   "type": "table",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 67 },
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-nodes\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, masterrinum, workerondemandnum, workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'gcp'  and \"reservedinstances\" = '1' and 'Yes' = '$purchase_option' and starttime = '$gcp_stime_month' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select displayname, masterondemandnum, \"\" as masterrinum, workerondemandnum, \"\" as workerrinum, totalcost from alameda_fedemeter..recommendation_jeri where granularity = '86400' and provider = 'gcp'  and \"reservedinstances\" = '0' and 'No' = '$purchase_option' and starttime = '$gcp_stime_month' and country = '$country'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}