apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: alameda
    component: alameda-ai-dispatcher
  name: alameda-ai-dispatcher
  namespace: alameda
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alameda
      component: alameda-ai-dispatcher
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alameda
        component: alameda-ai-dispatcher
    spec:
      containers:
      - env:
        - name: ALAMEDA_AI_DISPATCHER_DATAHUBADDRESS
          value: alameda-datahub.alameda:50050
        - name: ALAMEDA_AI_DISPATCHER_QUEUE_URL
          value: amqp://admin:adminpass@alameda-rabbitmq.alameda:5672
        image: jdcloudiaas/turta:ai-dispatcher
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/ai-dispatcher
            - probe
            - --type=liveness
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: ai-dispatcher
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/ai-dispatcher
            - probe
            - --type=readiness
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
