# This Dockerfile is used for building alameda-datahub on https://connect.redhat.com
FROM openshift/origin-release:golang-1.12 as builder
RUN yum update -y

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR /go/src/github.com/containers-ai/alameda

COPY . .

# Build datahub executable binary
RUN ["/bin/bash", "-c", "go build -ldflags \"-X main.VERSION=`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD``git diff --quiet || echo '-dirty'` -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`'\" -a -o ./datahub/datahub github.com/containers-ai/alameda/datahub/cmd"]

# Build license-utils executable binary
RUN ["/bin/bash", "-c", "go build -ldflags \"-X main.VERSION=`git rev-parse --abbrev-ref HEAD`-`git rev-parse --short HEAD``git diff --quiet || echo '-dirty'` -X 'main.BUILD_TIME=`date`' -X 'main.GO_VERSION=`go version`'\" -a -o ./datahub/license-utils github.com/containers-ai/alameda/datahub/tools/license-utils/cmd"]

# Copy the alameda-datahub into a thin image
FROM registry.access.redhat.com/ubi8/ubi-minimal
ENV SUMMARY="Alameda Datahub is an API gateway for handling gRPC requests."	\
    DESCRIPTION="Alameda Datahub is an API gateway for handling gRPC requests." \
    NAME="Alameda Datahub" \
    VERSION="latest" \
    USER_UID=1001 \
    USER_NAME=alameda \
    FEDAIHOME="/opt/prophetstor/federatorai" \
    LD_LIBRARY_PATH="/opt/prophetstor/federatorai/lib"

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="$NAME" \
      com.redhat.component="customer-container" \
      name="$NAME" \
      version="$VERSION" \
      vendor="ProphetStor Data Services, Inc."

# Copy datahub
COPY --from=builder /go/src/github.com/containers-ai/alameda/LICENSE /licenses/
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/etc/datahub.yml /etc/alameda/datahub/datahub.yml
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/datahub /usr/local/bin/

# Copy license-utils
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/license-utils /usr/local/bin/

# Copy keycode management tool
RUN mkdir -p -m ug+w /opt/prophetstor/federatorai/bin /opt/prophetstor/federatorai/lib /opt/prophetstor/federatorai/etc /opt/prophetstor/federatorai/var/tmp
RUN chown -R 1001:0 /opt/prophetstor/federatorai
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/pkg/account-mgt/keycodes/bin/license_main /opt/prophetstor/federatorai/bin/
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/pkg/account-mgt/keycodes/lib/license_helper.so /opt/prophetstor/federatorai/lib/
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/pkg/account-mgt/keycodes/lib/license_util.so /opt/prophetstor/federatorai/lib/
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/pkg/account-mgt/keycodes/lib/util_crypto.so /opt/prophetstor/federatorai/lib/
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/pkg/account-mgt/keycodes/lib/util_ldap.so /opt/prophetstor/federatorai/lib/
COPY --from=builder /go/src/github.com/containers-ai/alameda/datahub/pkg/account-mgt/keycodes/lib/_utilModule.so /opt/prophetstor/federatorai/lib/

EXPOSE 50050/tcp

RUN chown -R 1001:0 /etc/alameda && mkdir -p /var/log/alameda && chown -R 1001:0 /var/log/alameda && chmod ug+w /var/log/alameda

USER 1001
ENTRYPOINT ["/usr/local/bin/datahub", "run"]
